title: SURJA PRATIM BEJ
Mobile No.: 09471310476
Location: JAMSHEDPUR, JHARKHAND
Email: surjabej@gmail.com
logo: /assets/img/jay.jpg
show_downloads: true
theme: jekyll-theme-minimal
Link: https://www.linkedin.com/in/surja-bej-653365264
