title: SURJA PRATIM BEJ
Mobile No.: 09471310476
Location: JAMSHEDPUR, JHARKHAND
logo: /assets/img/jay.jpg
description: text below image
show_downloads: true
theme: jekyll-theme-minimal
#Link: [title](https://www.example.com)
