# Site settings
title: "Surja Pratim Bej - Resume Portfolio"
description: "Experienced Quality System Professional and Data Analysis Enthusiast seeking challenging roles."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io/resume-portfolio" # the base hostname & protocol for your site
