title: SURJA PRATIM BEJ
mobile_number: 09471310476
location: JAMSHEDPUR, JHARKHAND
email: surjabej@gmail.com
logo: /assets/img/jay.jpg
show_downloads: true
remote_theme: pages-themes/cayman@v0.1.1
theme: jekyll-theme-minimal
link: https://www.linkedin.com/in/surja-bej-653365264
